# Generated by Django 4.0.4 on 2022-05-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='label',
            field=models.CharField(default=1, max_length=30, verbose_name='Значение'),
            preserve_default=False,
        ),
    ]
